Annotations

diff --git a/.github/workflows/analyze-and-generate.yml b/.github/workflows/analyze-and-generate.yml
--- a/.github/workflows/analyze-and-generate.yml
+++ b/.github/workflows/analyze-and-generate.yml
@@ -40,19 +40,6 @@ jobs:
           name: coverage-report
           path: coverage/coverage.xml
 
-      - name: SonarCloud Scan
-        uses: sonarsource/sonarcloud-github-action@master
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        with:
-          args: >
-            -Dsonar.organization=jeanvalverde24
-            -Dsonar.projectKey=JeanValverde24_SI-8811-Pruebas_QA_U2_VALVERDE_CANO
-            -Dsonar.sources=TeamWebQaUPT
-            -Dsonar.python.coverage.reportPaths=coverage/coverage.xml
-            -Dsonar.inclusions=TeamWebQaUPT/webdriver_config.py,TeamWebQaUPT/utils.py
-
       - name: Fetch SonarCloud Metrics
         id: fetch-metrics
         run: |
@@ -60,8 +47,14 @@ jobs:
           PROJECT_KEY="JeanValverde24_SI-8811-Pruebas_QA_U2_VALVERDE_CANO"
           METRICS="bugs,vulnerabilities,code_smells,coverage,duplicated_lines_density,complexity,ncloc,cognitive_complexity,comment_lines_density,security_rating,reliability_rating,sqale_rating"
 
-          RESPONSE=$(curl -s -u $SONAR_TOKEN: "$SONAR_API_URL?component=$PROJECT_KEY&metricKeys=$METRICS")
+          RESPONSE=$(curl -s -u "$SONAR_TOKEN:" "$SONAR_API_URL?component=$PROJECT_KEY&metricKeys=$METRICS")
           echo "SonarCloud API Response: $RESPONSE"
+
+          if [[ -z "$RESPONSE" || "$RESPONSE" == *"errors"* ]]; then
+            echo "Error fetching SonarCloud metrics. Please check the project key and SonarCloud API token."
+            exit 1
+          fi
+
           echo "response=$RESPONSE" >> $GITHUB_ENV
 
       - name: Publish SonarCloud Metrics as Annotations
@@ -87,6 +80,19 @@ jobs:
           echo "| Maintainability      | $MAINTAINABILITY | :recycle: |" >> $GITHUB_STEP_SUMMARY
         env:
           response: ${{ env.response }}
+
+      - name: SonarCloud Scan
+        uses: sonarsource/sonarcloud-github-action@master
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        with:
+          args: >
+            -Dsonar.organization=jeanvalverde24
+            -Dsonar.projectKey=JeanValverde24_SI-8811-Pruebas_QA_U2_VALVERDE_CANO
+            -Dsonar.sources=TeamWebQaUPT
+            -Dsonar.python.coverage.reportPaths=coverage/coverage.xml
+            -Dsonar.inclusions=TeamWebQaUPT/webdriver_config.py,TeamWebQaUPT/utils.py
 
   publish-package:
     name: Publish Package
